version: "3.7"

services:
  webserver:
    build: .
    container_name: om30-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: Dockerfile.php_fpm
    container_name: om30-php-fpm-74
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm.ini:/etc/php7/fpm/pool.d/www.conf
    depends_on:
      - db

  db:
    image: mariadb:10.2.44
    container_name: om30-mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=om30
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql/init:/docker-entrypoint-initdb.d

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
