version: "3.7"

services:
  webserver:
    build: .
    container_name: om30-nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./htdocs:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  php:
    build:
      context: ./
      dockerfile: Dockerfile.php_fpm
    container_name: om30-php-fpm-74
    restart: always
    ports:
      - 9000:9000
    volumes:
      - ./htdocs:/var/www/html
      - ./php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm.ini:/etc/php7/fpm/pool.d/www.conf
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: om30-postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=om30
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
